baseURL = "http://example.org/"
languageCode = "de"
title = "Sternwarte Bad Kreuznach e.V."
# googleAnalytics = "UA-123-45"

[params]
    description = "This is the Sternwarte Website built with Hugo"

[[menu.main]]
    name = "Über uns"
    weight = 1

[[menu.main]]
    name = "VHS"
    url = "/vhs"
    weight = 2

[[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 3

[[menu.main]]
    name = "Galerie"
    url = "/galerie"
    weight = 4

[[menu.main]]
    name = "Infos"
    weight = 5

[[menu.main]]
    name = "Shop"
    url = "http://shop.spreadshirt.de/sternwarte-kreuznach/"
    weight = 6


[[menu.social]]
    name = "Facebook"
    url = "https://www.facebook.com/Sternwarte-Bad-Kreuznach-eV-1041582079283448"
    pre = "svg/027-facebook.svg"

[[menu.social]]
    name = "YouTube"
    url = "https://www.youtube.com/channel/UCiPx2XenNCDxbFA-XXnfnvg?sub_confirmation=1"
    pre = "svg/028-youtube.svg"