baseURL = "http://example.org/"
languageCode = "de"
title = "Sternwarte Bad Kreuznach e.V."
theme = "stubborn"
# googleAnalytics = "UA-123-45"

[params]
    description = "This is the Sternwarte Website built with Hugo"

[[menu.main]]
    name = "Über uns"
    url = "/ueber-uns"

[[menu.main]]
    name = "VHS"
    url = "/vhs"

[[menu.main]]
    name = "Blog"
    url = "/blog"

[[menu.main]]
    name = "Galerie"
    url = "/galerie"


[[menu.social]]
    name = "Facebook"
    url = "https://www.facebook.com/Sternwarte-Bad-Kreuznach-eV-1041582079283448"
    pre = "svg/027-facebook.svg"

[[menu.social]]
    name = "YouTube"
    url = "https://www.youtube.com/channel/UCiPx2XenNCDxbFA-XXnfnvg?sub_confirmation=1"
    pre = "svg/028-youtube.svg"