baseURL = "https://apeer.uber.space/"
languageCode = "de"
title = "Sternwarte Bad Kreuznach e.V."
summaryLength = 25

[imaging]
anchor = "center"

[params]
    description = "This is the Sternwarte Website built with Hugo"

[[menu.main]]
    weight = 1
    name = "Über uns"

[[menu.main]]
    weight = 2
    name = "VHS"
    url = "/vhs"

[[menu.main]]
    weight = 3
    name = "Blog"
    url = "/blog"

[[menu.main]]
    weight = 4
    name = "Galerie"
    url = "/galerie"

[[menu.main]]
    weight = 5
    name = "Öffnungszeiten"
    url = "/oeffnungszeiten"

[[menu.main]]
    weight = 6
    name = "Kontakt & Anfahrt"
    url = "/kontakt"


[[menu.social]]
    name = "Facebook"
    url = "https://www.facebook.com/Sternwarte-Bad-Kreuznach-eV-1041582079283448"
    pre = "svg/027-facebook.svg"

[[menu.social]]
    name = "YouTube"
    url = "https://www.youtube.com/channel/UCiPx2XenNCDxbFA-XXnfnvg?sub_confirmation=1"
    pre = "svg/028-youtube.svg"