backend:
  name: github
  repo: alexanderpeerdeman/sternwarte-kreuznach.de
media_folder: static/uploads
public_folder: /uploads
site_url: https://sternwarte-kreuznach.de
logo_url: https://sternwarte-kreuznach.de/svg/logo.svg
locale: "de"
collections:
  - label: "Blog"
    name: "blog"
    folder: "content/blog"
    create: true
    media_folder: ""
    public_folder: ""
    nested:
      depth: 3
    # slug: "{{year}}/{{slug}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - {
          label: "Veröffentlichungsdatum",
          name: "date",
          widget: "datetime",
          date_format: "DD. MMMM YYYY",
          time_format: "HH:mm:ss",
        }
      - { label: "Bild", name: "images", widget: "image", choose_url: false }
      - { label: "Zusammenfassung", name: "summary", widget: "string" }
      - { label: "Inhalt", name: "body", widget: "markdown" }
